### PR TITLE
add pings to webhook

### PR DESCRIPTION
**Pull request by pifopi**
Hello !

I did some changes on my fork and because I thought they could be useful, I decided to share them. Here is the first PR with the ability to add pings to webhook. I am very unexperimented with C# designer so feel free to report any issue !

I'll try to create a PR to add form filtering then.

Thanks in advance !

### CODE REVIEW

**Comment by architdate** [comment]
This probably needs to account for spam possibilities. I'm unsure if `everyone` and `here` roles also have IDs that need to be accounted for

**Comment by pifopi** [comment]
How cod I do this ? From my knowledge, webhook are pretty insecure by design. Bot have more security options. Not everyone can get a webhook though, so if a server give webhook without any check, yes some bad stuff could happen to them

**Comment by pifopi** [comment]
I couldn't find any information about id for those mentions. Writing @everyone and @here in plain text works though.

**Comment by PokeFlexii** [comment]
is it possible to send a text message along with the screenshot ?

**Comment by pifopi** [comment]
what screenshot ? From the button uin the UI ? If yes, that PR has nothing to do with it

**Comment by LegoFigure11** [comment]
> I mean via the code itself we would need to check if something resolves to everyone or here. Regarding a discord bot, I have no intention of making it myself but I believe @LegoFigure11 was keen on it

Yeah, I do plan on adding Discord bot functionality at some point. For now though, I think the best way to handle this would just be to have a string input in the settings where you can define your own message (and include pings and such there), similar to the "Show an alert window with the following message" setting we already have. Gives a little more customisability than restricting it to a single user or role ping as it is currently.

If server owners are adding untrusted webhooks to their server then that's on them, I don't think it's our responsibility to restrict everyone/here pings on our end.

**Comment by pifopi** [comment]
Thanks, it is indeed much better ! Also thanks to violent spatula for teaching me to use the designer (instead of manually adding 27 pixels everywhere)

**Pull request merged**
