### PR TITLE
Adds configuration for emoji + square shiny detection

### PR DESCRIPTION
**Pull request by ViolentSpatula**
Add emoji to save data
Add emoji config button to settings/webhook
Add EmojiConfig popup window
Add Square Shiny filter (filter tested and working)
Add Square Shiny detection to webhook (temp emoji is literally garbage)

image
image
image
image

### CODE REVIEW

**Comment by architdate** [comment]
Love the emoji config, but why do we care about square vs regular shinies here? only SWSH differentiates the shiny type, since then visually both shinies have been the same.

**Comment by ViolentSpatula** [comment]
It's been a common request so I added it

**Comment by jnovack** [comment]
I have quite a number of garbage shinies. Now I want garbage SQUARE shinies!

**Comment by jnovack** [comment]
That square is just still too confusing.  It looks like the icon didn't load.

image

**Comment by jnovack** [comment]
so, I caught what was calculated as a square shiny, but it did not square when I threw him into a raid.

can anyone confirm they actually have a square shiny?

**Comment by architdate** [comment]
> They're square only in your own mind

image

> Very neat changes, I loved the emotes before the rollback !

I believe you can add them back with this change (just copy over the older emote strings and it should work)

**Pull request merged**
