### PR TITLE
Adds test webhook button

### LINKED ISSUE #94: [Feature Request] Test webhook
Probably a simple thing to add a button to test the web hook so you can see that it worked instead of waiting for it to fire

Even better then just having it put "this worked" in a web hook would be sending an example, IE just have a json file or some other holder of a standard pokemon to send though the web hook for testing changes to it like how the icons look or the IV's ect

### PR DESCRIPTION
**Pull request by jnovack**
Closes #94 

Adds a test webhook button which sends the currently selected pokemon as a notification (doubles as a "look what I found but didn't match my filter" button).

Please review and ensure it works as expected.

### CODE REVIEW

**Comment by LegoFigure11** [comment]
Is this necessary? The screenshot button can already be used to test the webhook

**Comment by jnovack** [comment]
But it can't test what the notification will look like when you start messing with all the options.

**Comment by ViolentSpatula** [comment]
I also agree that a test webhook function is useful when setting up your webhook to appear the way you want it to.

**Comment by architdate** [comment]
@jnovack can you fix the merge conflicts for this? i'll review once that is done!

**Comment by jnovack** [comment]
Boo!

Yes, I will.

**Comment by architdate** [comment]
Seems like the CI failed

**Comment by jnovack** [comment]
Yes, not ready yet.  I had no way of pushing intermediate commits without also showing up here in this PR.  I work across multiple machines.  I'll @ mention you when ready.

**Comment by jnovack** [comment]
How did the last PR pass builds?  I'm getting an error here https://github.com/LegoFigure11/RaidCrawler/blob/main/Subforms/ConfigWindow.cs#L8

Line 8 wasn't linted, and Line 9 just flat out errors.
`CS0501 "ConfigWindow.ConfigWindow(Config)" must declare a body because it is not marked abstract, extern, or partial."`

**Comment by jnovack** [comment]
@architdate There's a serious issue with main, I have 10 errors from the last merge.  Was it not checked?  Can we chat on Discord?  Send an email to my commit email address with an invite please.

**Comment by architdate** [comment]
I have no errors on the latest commit, weird. Anyway feel free to msg me on discord @thecommondude#8240 or join PDP https://discord.gg/tDMvSRv (#general-raidchat)

**Pull request closed without merging**
