### PR TITLE
USB & refactor

### PR DESCRIPTION
**Pull request by Koi-3088**
In-progress PR that adds USB connectivity alongside a refactor and various optimizations. End-goal is to split the currently single `csproj` and structure for long-term maintenance and readability.

### CODE REVIEW

**Comment by Koi-3088** [comment]
Assuming no issues, final commit(s) should just be minor fixes (if found) and single-file build.

**Comment by Koi-3088** [comment]
Date advance timings are still inconsistent, need further testing and calibration.

Apart from that, in no particular order:

Date Advance:
 - Stop button added for date advance.
 - Date advance success/attempts added to StreamerView.
 - Changed how the progress bar works for date advance.
 
StreamerView/General:
 - Form display added.
 - StreamerView can be toggled on demand.

Connectivity:
 - USB connectivity added.

Misc:
 - Most functions made to be asynchronous.
 - Solution split into 2 projects, a lot of methods moved around and/or extended.
 - Pointers/offsets cached for faster reads.
 - Tons of dialog and message boxes switched to display on main thread.
 - "Save" buttons removed, all settings should update via the FormClosing event.
 - Single-file GitHub action build added.
 - Slightly optimized flatbuffers and Json reading by switching to pkNX's methods (thanks to Kurt) and System.Text.Json.
 - Make screenshots work for both USB and WiFi.
 - Probably a bunch of other things I forget.

**Comment by LegoFigure11** [comment]
Timings weren't exactly consistent before either, so no change there 😅 

Thanks so much for this Koi! I really appreciate it. I'll merge now and push a new release within a couple of days if nothing pressing is found.

**Comment by Koi-3088** [comment]
I'll keep an eye on issues, and feel free to ping or DM me on Discord if you spot issues, I'll fix.

**Pull request merged**
