### PR TITLE
"Streamer" View a.k.a. 10-Foot Interface

### PR DESCRIPTION
**Pull request by jnovack**
This is a work-in-progress branch I am soliciting feedback on.  I would ultimately like it to be merged upstream, but not without it having parity.

Please feel free to do code reviews and comments with suggestions.

image

_Issue_
I stream the searching, and the current interface is.. umm.. less than optimal.   I am designing a newer interface that can be easily shown on a stream so the progress and details are easily viewed.  I can share the additional window independently with only the information the viewer needs or may want.  The main window will not be replaced, this is merely a read-only display window.

The goal is to have a window that is readable from a phone over your streaming service of choice.

_To Use_
Within Settings, you must select "Experimental View" and restart (to make things simple).  To close the additional window, double click in any non-label/textbox area.  This is working, please download and try it.

### CODE REVIEW

**Comment by architdate** [comment]
Just a suggestion maybe to centre the map vertically? The unused whitespace below it is kind of jarring :)

**Comment by jnovack** [comment]
The blank space is where the item drops will be so you can see them.

**Comment by architdate** [comment]
> The blank space is where the item drops will be so you can see them.

That sounds reasonable enough! I like the general UI design in the original image, so when it's ready for review just let me know and I'll review and merge :)

**Comment by jnovack** [comment]
Ok, v1.0 has been completed.  
image

I want to get it in people's hands to get real feedback.  I have more that I'd like to do, but this is working and acceptable to a user.

**Comment by architdate** [comment]
image
I think it might be better to make it clear that the top 4 moves are the moveset and the bottom 4 are extras

**Comment by jnovack** [comment]
What about "Raid Moveset"?  I don't see a point in splitting the moves into "moveset" and "extras".  The raid pokemon uses all of them, and when you capture it, the pokemon knows all of them (you have to remember the extras).  I don't feel it matters that they are split.

**Comment by architdate** [comment]
> What about "Raid Moveset"? I don't see a point in splitting the moves into "moveset" and "extras". The raid pokemon uses all of them, and when you capture it, the pokemon knows all of them (you have to remember the extras). I don't feel it matters that they are split.
> 
> At best, I'll call the box "Raid Moveset" and mute the bottom 4 in color. Again, it's not the primary interface, it's the kiosk interface, just has to look pleasing to the eye.

Muting the bottom 4 in color sounds great, or slightly altering the background color for bottom 4 to a light greyish tone may work. Apart from that, it all looks solid to me!

**Comment by jnovack** [comment]
image

Good to squash and sign?

As a reminder, I already have the next set of tweaks (restructuring the design to add bottlecaps and capsules, changing tera icons, moving of some fields around depending on importance, fonts, etc) in the pipeline, I just want to get this into main so I can start my next branch fresh.

**Comment by jnovack** [comment]
Official Feature List:

* Streamer ["10-foot-interface"](https://en.wikipedia.org/wiki/10-foot_user_interface) redesign to augment main interface view.
* Hides "programmer" details (still available in main interface) from public view.
* Details, Rewards and Map in one "single-pane-of-glass" view.
* Searching bar at the bottom of the screen to mimic progress.
* Experimental view, not on by default.

The design is meant to be a 16:9 non-interactive/display only, showing only the details most cared about by stream viewers or casual users.  It is meant to be mostly readable when viewed full-screen on a phone or TV at a distance.

**Comment by LegoFigure11** [comment]
Can we include the type image files in raidcrawler rather than having to resolve them from the URL every time? Might just be my slow connection but there's a noticeable delay in it updating when scrolling through the raids.



Aside from that this looks and feels great! Thank you for making it.

**Comment by LegoFigure11** [comment]
Changing the herba assets also messes up display of the Rewards View and Item ID helper windows

**Comment by jnovack** [comment]
* fixed Rewards View and Item ID helper windows by using hi-res icons everywhere.
* included the tera type image files
* re-structured windows to put stars under teratype icon.  Feels better.

**Comment by LegoFigure11** [comment]
Ability Capsule and Bottle Cap are still invisible in RewardsView


Ability Patch and Herbas are very distorted in RewardsView, as well as all icons in ItemIDs



Additionally all of the other sprites in RewardsView are now a little fuzzy, likely because of changing `PictureBoxSizeMode.CenterImage` to `PictureBoxSizeMode.Zoom`? If we could change that back to `CenterImage` to fix these regressions that'd be great. I don't mind if you need to add the hi-res images as separate resources instead of trying to reuse them for the TeraRaidView window as well.

One other small thing I noticed was the taskbar icon, if that could be changed to use `MightiestMark.ico` then that'd be great as well.


Once that's all done I'll be happy to merge, unless @architdate has anything else to add? I've been playing around with it for a while now and had some other people trying it out too, and the feedback has been nothing but positive so far. Thanks again for all the time you've put in to this!

**Comment by jnovack** [comment]
> Ability Capsule and Bottle Cap are still invisible in RewardsView
> Ability Patch and Herbas are very distorted in RewardsView, as well as all icons in ItemIDs

Fixed
image

> One other small thing I noticed was the taskbar icon, 

Fixed
image

> Thanks again for all the time you've put in to this!

My pleasure! I'm glad you were receptive to my ideas.

**Comment by architdate** [comment]
> Once that's all done I'll be happy to merge, unless @architdate has anything else to add? I've been playing around with it for a while now and had some other people trying it out too, and the feedback has been nothing but positive so far. Thanks again for all the time you've put in to this!

Seems solid to me 👍

**Comment by LegoFigure11** [comment]
Thanks!

**Pull request merged**
