### PR TITLE
add About Tab and unclutter Main UI

### PR DESCRIPTION
**Pull request by jnovack**
Massive changes.

* Added an About Tab which pulls from GitVersion.
* Added a General Tab with Game Information (shouldn't this be read-only since we set it??)
* Moved Game Information (which rarely changes) out of Main UI
* Moved Turdlets of Information into Game Information's old spot to declutter.
* Added "Open Map" button for simpler user experience (I literally had to get the code to know that I could click the location)

image

image

image

### CODE REVIEW

**Comment by architdate** [comment]
Maybe @LegoFigure11 can also look at this and add/amend more suggestions? I believe this is likely the last overhaul to the UI that will be done so best to get it right :)

**Comment by jnovack** [comment]
Yes, absolutely, this is a draft, and looking for feedback!

As I said in another PR, I'm a filthy casual, I don't have the years of experience you have with all the lingo.  I am literally 3 weeks into this entire journey (received my RCM jig just before New Years, and my last played Pokemon game was Fire Red).  I'm approaching this application from a "filthy casual" point of view and trying to cater that person.

> day skip success rate can go in the settings/Match tab since that is where most delays are located and it will let people see their failure rate at a glance when making changes

Yep, willfix.

> the raid count and shiny count can go back to the top.

Do you NEED the raid count? The number of raids is literally 136 pixels away in the selection box.

> Search time can be part of the status when when it is completed (does it need to keep ticking or does it just need to show the time at the end, for eg: Status: Completed [00:02:15]. If we need to show constant ticking time it can be shown on the form header itself beside the date)

I like the constant changing form header. 

> With new space opened up after moving general settings we can have a groupbox called "Raid Controls" which would house buttons for Dump Raid, Rewards, Screenshot and Pull Events

Yes, let me move some things around.

> possible additional features

After this is merged, we can iterate on the enhancements.

**Comment by jnovack** [comment]
I hate all of you.

image

**Comment by jnovack** [comment]
@architdate 

image

**Comment by jnovack** [comment]
I have painstakingly aligned as much as much as could before wanting to throw myself through the window.

I think I'm good.

**Comment by architdate** [comment]
> I hate all of you.
> 
> image

Lmfao

**Comment by architdate** [comment]
I think this looks quite solid! @LegoFigure11 can you review incase you have any comments? If not we can merge this

**Comment by architdate** [comment]
I'll merge for now and then we can keep making changes as we proceed

**Pull request merged**
