### PR TITLE
Add setting to overshoot "Date and Time" by one, then DUP to recover.

### PR DESCRIPTION
**Pull request by zyro670**
Allows for quicker scrolling and configurable among different Switches. From tests: 800 for Lite, 950 for OLED. 900-950 for V1.

### CODE REVIEW

**Comment by LegoFigure11** [comment]
This works great, thanks Zyro!

Could you please change it to remove the "DDOWN inputs" setting  well? once that's done I'll gladly merge this.

**Review by jnovack — COMMENTED** [review]
What's going on with all these spacing changes?  Which editor are you using that is doing this?

I don't want every committed file to be bouncing back and forth with spacing changes among all of us.

**Comment by pifopi** [comment]
It looks like a merge issue to me. I do not think zyro added those on purpose

**Comment by architdate** [comment]
This can be merged once conflicts are resolved, seems like some spacing issues which can be easily fixed and some UI issue which may need to be fixed by zyro

**Comment by jnovack** [comment]
This is nice, seems to take about 750ms off each search?

Pre-Commit =~ 18.80s (avg)
Post-Commit =~ 18.15s (avg)

Anyone getting better results?

**Comment by pifopi** [comment]
I do have much quicker search results with those :
image

Those are settings close to what all SHA hosts use. It gives around 12s. Also added a check that the raids changed on my fork and tracking that with a counter, I'm at 1125/1125 right now

**Comment by zyro670** [comment]
Hi sorry wasn't able to get to it last few days. I'll resubmit this weekend.

**Comment by jnovack** [comment]
> Re-open game delay.  `1500`

I had an issue with this because of the "Checking to see if this software can be played." message on screen.  I use digital downloads and have multiple switches.  Had to bump it to `4000`

**Comment by jnovack** [comment]
> Hi sorry wasn't able to get to it last few days. I'll resubmit this weekend.

It's already in, but since you have some free time, do you not take feature requests/bug reports for your SysBot fork?  

Once we get this in a good place, I wanted to come see if I could help you out but Github doesn't auto-enable Issues for forks, and I wanted to discuss things before starting to submit.

**Pull request closed without merging**
